// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "forestBalance_types.h"
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cg_solve_cpp
Rcpp::NumericVector cg_solve_cpp(Rcpp::S4 Z_s4, Rcpp::NumericVector rhs_r, double tol, int maxiter);
RcppExport SEXP _forestBalance_cg_solve_cpp(SEXP Z_s4SEXP, SEXP rhs_rSEXP, SEXP tolSEXP, SEXP maxiterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type Z_s4(Z_s4SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rhs_r(rhs_rSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    rcpp_result_gen = Rcpp::wrap(cg_solve_cpp(Z_s4, rhs_r, tol, maxiter));
    return rcpp_result_gen;
END_RCPP
}
// get_leaf_nodes_cpp
IntegerMatrix get_leaf_nodes_cpp(List forest, NumericMatrix newdata);
RcppExport SEXP _forestBalance_get_leaf_nodes_cpp(SEXP forestSEXP, SEXP newdataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type forest(forestSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type newdata(newdataSEXP);
    rcpp_result_gen = Rcpp::wrap(get_leaf_nodes_cpp(forest, newdata));
    return rcpp_result_gen;
END_RCPP
}
// build_Z_cpp
List build_Z_cpp(IntegerMatrix leaf_matrix);
RcppExport SEXP _forestBalance_build_Z_cpp(SEXP leaf_matrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type leaf_matrix(leaf_matrixSEXP);
    rcpp_result_gen = Rcpp::wrap(build_Z_cpp(leaf_matrix));
    return rcpp_result_gen;
END_RCPP
}
// remap_leaves_cpp
IntegerMatrix remap_leaves_cpp(IntegerMatrix leaf_matrix);
RcppExport SEXP _forestBalance_remap_leaves_cpp(SEXP leaf_matrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type leaf_matrix(leaf_matrixSEXP);
    rcpp_result_gen = Rcpp::wrap(remap_leaves_cpp(leaf_matrix));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_forestBalance_cg_solve_cpp", (DL_FUNC) &_forestBalance_cg_solve_cpp, 4},
    {"_forestBalance_get_leaf_nodes_cpp", (DL_FUNC) &_forestBalance_get_leaf_nodes_cpp, 2},
    {"_forestBalance_build_Z_cpp", (DL_FUNC) &_forestBalance_build_Z_cpp, 1},
    {"_forestBalance_remap_leaves_cpp", (DL_FUNC) &_forestBalance_remap_leaves_cpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_forestBalance(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
